# Generated by Django 2.2.4 on 2020-10-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.IntegerField(default=0.0)),
                ('temp', models.IntegerField(default=0.0)),
                ('humid', models.IntegerField(default=0.0)),
                ('pressure', models.IntegerField(default=0.0)),
                ('pm2_5', models.IntegerField(default=0.0)),
                ('pm10', models.IntegerField(default=0.0)),
                ('wind', models.IntegerField(default=0.0)),
            ],
        ),
    ]
