# Generated by Django 2.2.4 on 2020-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstation',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
