# Generated by Django 2.2.4 on 2021-02-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('temp', models.FloatField(default=0.0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('pm1', models.FloatField(default=0.0)),
                ('pm2_5', models.FloatField(default=0.0)),
                ('pm10', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='weatherhistory',
            options={'ordering': ['id', '-date_created']},
        ),
        migrations.RenameField(
            model_name='listnamestation',
            old_name='name_stations',
            new_name='name',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pm1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pm10',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pm2_5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='humidity',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='humidity_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='humidity_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='humidity_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm10',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm10_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm10_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm10_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm2_5',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm2_5_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm2_5_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm2_5_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pressure',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pressure_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pressure_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pressure_min',
            field=models.FloatField(default=0.0),
        ),
    ]
