# Generated by Django 2.2.4 on 2020-10-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0.0)),
                ('time', models.FloatField(default=0.0)),
                ('pressure', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('wind_direction', models.FloatField(default=0.0)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('wind_gust', models.FloatField(default=0.0)),
                ('rain_1h', models.FloatField(default=0.0)),
                ('rain_24h', models.FloatField(default=0)),
                ('rain_mn', models.FloatField(default=0.0)),
                ('luminosity', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='reportstation',
            old_name='humid',
            new_name='lasttime',
        ),
        migrations.RenameField(
            model_name='reportstation',
            old_name='location',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='reportstation',
            name='pm10',
        ),
        migrations.RemoveField(
            model_name='reportstation',
            name='pm2_5',
        ),
        migrations.RemoveField(
            model_name='reportstation',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='reportstation',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='reportstation',
            name='wind',
        ),
        migrations.AddField(
            model_name='reportstation',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reportstation',
            name='type',
            field=models.CharField(choices=[('a', 'AIS'), ('l', 'APRS station'), ('i', 'APRS item'), ('o', 'APRS object'), ('w', 'weather station')], default='', max_length=5),
        ),
    ]
