# Generated by Django 2.2.4 on 2021-02-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('pm1', models.FloatField(default=0.0)),
                ('pm2_5', models.FloatField(default=0.0)),
                ('pm10', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='listnamestation',
            old_name='name_stations',
            new_name='name',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pm1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pm10',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pm2_5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1_min',
            field=models.FloatField(default=0.0),
        ),
    ]
