# Generated by Django 2.2.4 on 2020-10-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20201011_0417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='WeatherData',
        ),
    ]
