# Generated by Django 2.2.4 on 2021-03-18 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210318_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstation',
            name='date_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='date_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='date_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
