# Generated by Django 2.2.4 on 2021-03-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210308_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportstation',
            options={'ordering': ['id']},
        ),
    ]
