# Generated by Django 2.2.4 on 2021-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210322_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastweather',
            old_name='temp',
            new_name='model_score',
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='date_next_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='date_next_twoday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='temp_next_day',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='temp_next_twoday',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
