# Generated by Django 2.2.4 on 2021-03-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210309_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportstation',
            options={},
        ),
    ]
