# Generated by Django 2.2.4 on 2021-04-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210331_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherhistory',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='day',
            field=models.CharField(default='', max_length=60),
        ),
    ]
