# Generated by Django 2.2.4 on 2021-03-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210309_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportstation',
            options={'ordering': ['-id']},
        ),
    ]
