# Generated by Django 2.2.4 on 2020-10-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20201011_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstation',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
