# Generated by Django 2.2.4 on 2021-04-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20210402_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstation',
            name='date_timestamp',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='date_timestamp',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='date_timestamp',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='humidity_avg',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='pm10_avg',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='pm1_avg',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='pm2_5_avg',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='pressure_avg',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='temp_avg',
        ),
        migrations.AddField(
            model_name='reportstation',
            name='day',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='day',
            field=models.CharField(default='', max_length=60),
        ),
    ]
