# Generated by Django 2.2.4 on 2021-03-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20210309_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportstation',
            options={'ordering': ['id']},
        ),
    ]
