# Generated by Django 2.2.4 on 2021-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20210402_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherhistory',
            name='humidity_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm10_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm1_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pm2_5_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='pressure_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='temp_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
