# Generated by Django 2.2.4 on 2021-03-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20210309_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherhistory',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='forecastweather',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='history_id',
        ),
    ]
