# Generated by Django 2.2.4 on 2021-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20210311_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
