# Generated by Django 2.2.4 on 2020-10-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20201011_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
