# Generated by Django 2.2.4 on 2021-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20210311_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstation',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='date_created',
        ),
        migrations.AddField(
            model_name='reportstation',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherhistory',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
