# Generated by Django 2.2.4 on 2020-10-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_weatherdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_avg', models.FloatField(default=0.0)),
                ('temp_max', models.FloatField(default=0.0)),
                ('temp_min', models.FloatField(default=0.0)),
            ],
        ),
    ]
