# Generated by Django 2.2.4 on 2020-10-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_weatherhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstation',
            name='type',
            field=models.CharField(choices=[('a', 'AIS'), ('l', 'APRS station'), ('i', 'APRS item'), ('o', 'APRS object'), ('w', 'weather station')], default='', max_length=16),
        ),
    ]
