# Generated by Django 2.2.4 on 2021-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20210312_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstation',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='weatherhistory',
            name='date_time',
        ),
    ]
