# Generated by Django 2.2.4 on 2021-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20210312_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstation',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
