# Generated by Django 2.2.4 on 2021-03-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_auto_20210312_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
